### PR TITLE
add PDF option without depending on 'dbtoepub-ns'

### PR DESCRIPTION
**Pull request by siriobalmelli**
Thank you for making this!

Unfortunately I couldn't find a PDF version anywhere ... purchased it on Kobo but they are forcing me to use their app it seems, unhappy with that.

So I added a small snippet to build a PDF so I can add this to my library.
Again, much appreciated.

### CODE REVIEW

**Comment by mpoullet** [comment]
Very nice, but on my Ubuntu 16.04 with
```
pandoc --version
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
```
I had to use `--latex-engine` instead of `--pdf-engine`.
```
diff --git a/Makefile b/Makefile
index 4d64657..bf9140e 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ mythbuster.epub: $(SOURCES)
 
 mythbuster.pdf: stylesheets/passthrough.xsl main.docbook
        $(XSLTPROC) --xinclude $^ \
-               | pandoc --pdf-engine=xelatex -s -f docbook -o $@
+               | pandoc --latex-engine=xelatex -s -f docbook -o $@
 
 clean:
        rm -rf *~ *.olinkdb public epub mythbuster.epub mythbuster.pdf
```

**Comment by siriobalmelli** [comment]
Thanks for the info!
Turns out that on pandoc v2.2.1 which I'm running here, --latex-engine throws an error.

Added an if-test in the Makefile so that it will work with both.

**Comment by mpoullet** [comment]
Thanks. Maybe add `mythbuster.pdf` to the `.gitignore` file too.
```
diff --git a/.gitignore b/.gitignore
index d67c1bb..f1986ae 100644
--- a/.gitignore
+++ b/.gitignore
@@ -12,4 +12,5 @@ configure.wrong
 epub/
 generate
 mythbuster.epub
+mythbuster.pdf
 public/
```

**Comment by mpoullet** [comment]
Perfect! I hope it gets merged.

**Comment by siriobalmelli** [comment]
saw this wasn't merged yet and it had a trivial conflict; rebased and force-pushed

**Pull request closed without merging**
